import = [
    "~/.config/alacritty/themes/themes/pencil_dark.toml"
]

[font]
size = 12

  [font.normal]
  family = "MesloLGS NF"
  style = "Regular"

  [font.bold]
  family = "MesloLGS NF"
  style = "Bold"

  [font.italic]
  family = "MesloLGS NF"
  style = "Italic"

  [font.bold_italic]
  family = "MesloLGS NF"
  style = "Bold Italic"

